title: Portfolio
author: Francisco Pena
email: f.pena@columbia.edu
description: > # this means to ignore newlines until "baseurl:"
  A place to showcase my data science skills.
theme: minima
# social links
linkedin_username: franciscoxpena
github_username:  fxpena # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
